# Generated by Django 5.2.5 on 2025-09-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
