# Generated by Django 5.2.5 on 2025-08-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_failed_login_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
