# Generated by Django 5.2.5 on 2025-08-26 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordhistory',
            old_name='password',
            new_name='password_hash',
        ),
    ]
