# Generated by Django 5.2.5 on 2025-09-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_country_alter_address_country_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('VENDOR', 'Vendor'), ('STAFF', 'Staff'), ('SUPERADMIN', 'Superadmin')], default='USER', max_length=50),
        ),
    ]
